// Create a live daily summary with the new improved template
const admin = require('firebase-admin');

admin.initializeApp({
  credential: admin.credential.applicationDefault()
});

// Use the correct database
const db = admin.firestore();
db.settings({ databaseId: 'planwithhands' });

async function createLiveSummary() {
  console.log('🚀 Creating live daily summary with improved template...');
  
  try {
    // Use Flawless Pubs for testing (smaller org)
    const orgId = 'vnE0olvi1Tswjtdb19MI';
    const today = new Date();
    const todayStr = today.toISOString().split('T')[0];
    
    console.log(`\n📋 Creating live summary for ${todayStr}...`);
    
    // Get admin user
    const adminQuery = await db
      .collection('users')
      .where('organizationId', '==', orgId)
      .where('userRole', 'in', [1, 2])
      .where('isActive', '==', true)
      .limit(1)
      .get();
    
    if (adminQuery.docs.length === 0) {
      console.log('❌ No admin users found');
      return;
    }
    
    const adminDoc = adminQuery.docs[0];
    const adminData = adminDoc.data();
    
    // Create notification that will trigger the Cloud Function
    const notificationRef = db
      .collection('organizations')
      .doc(orgId)
      .collection('notifications')
      .doc();
    
    const notificationData = {
      title: `Daily Notes Summary - ${today.toLocaleDateString('en-US', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })}`,
      message: 'Daily summary report with improved format - generated by new template system',
      userId: adminDoc.id,
      type: 'general',
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      readBy: [],
      archivedBy: [],
      targetType: 'user',
      targetId: adminDoc.id,
      liveTest: true, // Mark as live test
      improvedTemplate: true, // Mark as using new template
      targets: {
        userRole: [1, 2],
        userId: [adminDoc.id]
      },
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
    };
    
    await notificationRef.set(notificationData);
    
    console.log('✅ Live daily summary notification created!');
    console.log(`   Organization: Flawless Pubs`);
    console.log(`   Admin: ${adminData.firstName} ${adminData.lastName}`);
    console.log(`   Date: ${todayStr}`);
    
    // Mark as sent in logs
    const logRef = db
      .collection('organizations')
      .doc(orgId)
      .collection('daily_summary_logs')
      .doc(todayStr);
    
    await logRef.set({
      date: todayStr,
      sentAt: admin.firestore.FieldValue.serverTimestamp(),
      organizationId: orgId,
      improvedTemplate: true,
      liveTest: true,
      expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000)
    });
    
    console.log('✅ Daily summary log updated');
    
    console.log('\n🎯 What to expect:');
    console.log('1. ⚡ Shorter, more scannable format');
    console.log('2. 🎭 Performance-based emoji and messaging');
    console.log('3. 📱 Mobile-friendly layout');
    console.log('4. 🎯 Actionable next steps');
    console.log('5. 🏆 Positive reinforcement for good performance');
    console.log('6. ⚡ Only shows the most important items');
    
    console.log('\n📱 Check the notifications page in the app to see the new format!');
    
  } catch (error) {
    console.error('❌ Error creating live summary:', error);
  }
  
  process.exit(0);
}

createLiveSummary();
