// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYzHMKb-VI9W2bz2MPQzVevH58YFAM6A',
    appId: '1:948527720669:web:6c46317a79c64ea0ba9334',
    messagingSenderId: '948527720669',
    projectId: 'plan-with-hands',
    authDomain: 'plan-with-hands.firebaseapp.com',
    storageBucket: 'plan-with-hands.firebasestorage.app',
    measurementId: 'G-NQ57SGRHWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9ydPiUXB_qwv3r9FnzimixyCl2Rlz7A',
    appId: '1:948527720669:android:a94ba3a6a0036547ba9334',
    messagingSenderId: '948527720669',
    projectId: 'plan-with-hands',
    storageBucket: 'plan-with-hands.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATMTdvZkoxuoMiGDxPCc7Jxk3Z6oXBUcY',
    appId: '1:948527720669:ios:9b42e5a6ae865655ba9334',
    messagingSenderId: '948527720669',
    projectId: 'plan-with-hands',
    storageBucket: 'plan-with-hands.firebasestorage.app',
    iosBundleId: 'com.example.handsClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATMTdvZkoxuoMiGDxPCc7Jxk3Z6oXBUcY',
    appId: '1:948527720669:ios:9b42e5a6ae865655ba9334',
    messagingSenderId: '948527720669',
    projectId: 'plan-with-hands',
    storageBucket: 'plan-with-hands.firebasestorage.app',
    iosBundleId: 'com.example.handsClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIYzHMKb-VI9W2bz2MPQzVevH58YFAM6A',
    appId: '1:948527720669:web:5bd1ef5be8a88a0eba9334',
    messagingSenderId: '948527720669',
    projectId: 'plan-with-hands',
    authDomain: 'plan-with-hands.firebaseapp.com',
    storageBucket: 'plan-with-hands.firebasestorage.app',
    measurementId: 'G-F6TK9E5D7P',
  );
}
