// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTpidNnWhAhsJrp81ICRoJd_4f57TYmYk',
    appId: '1:960378428314:web:9d46f0045b848db0a4f823',
    messagingSenderId: '960378428314',
    projectId: 'handstest-3c95b',
    authDomain: 'handstest-3c95b.firebaseapp.com',
    storageBucket: 'handstest-3c95b.firebasestorage.app',
    measurementId: 'G-0L6D9H5DE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwe3EikYMnjjFLzxmnKIBlaUSFYVOjhI',
    appId: '1:960378428314:android:184053b56b1ee805a4f823',
    messagingSenderId: '960378428314',
    projectId: 'handstest-3c95b',
    storageBucket: 'handstest-3c95b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bUwl8cNDiGApUgFspAPChDRX9SL4oj8',
    appId: '1:960378428314:ios:7b975be166f95cc8a4f823',
    messagingSenderId: '960378428314',
    projectId: 'handstest-3c95b',
    storageBucket: 'handstest-3c95b.firebasestorage.app',
    iosBundleId: 'com.example.handsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4bUwl8cNDiGApUgFspAPChDRX9SL4oj8',
    appId: '1:960378428314:ios:7b975be166f95cc8a4f823',
    messagingSenderId: '960378428314',
    projectId: 'handstest-3c95b',
    storageBucket: 'handstest-3c95b.firebasestorage.app',
    iosBundleId: 'com.example.handsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTpidNnWhAhsJrp81ICRoJd_4f57TYmYk',
    appId: '1:960378428314:web:cba6f027557b82c3a4f823',
    messagingSenderId: '960378428314',
    projectId: 'handstest-3c95b',
    authDomain: 'handstest-3c95b.firebaseapp.com',
    storageBucket: 'handstest-3c95b.firebasestorage.app',
    measurementId: 'G-Q2JYNGQWKD',
  );

}